# Generated by Django 2.2 on 2020-04-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_img/default.png', upload_to='profile_img'),
        ),
    ]
