# Generated by Django 2.2 on 2020-04-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
